---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoom
  namespace: kubedoom # SA lives in kubedoom namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom
  namespace: kubedoom-monsters   # permissions only in target
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom
  namespace: kubedoom-monsters   # bind Role in target
subjects:
  - kind: ServiceAccount
    name: kubedoom
    namespace: kubedoom   # SA lives in kubedoom namespace
roleRef:
  kind: Role
  name: kubedoom
  apiGroup: rbac.authorization.k8s.io