---
apiVersion: v1
kind: Service
metadata:
  name: kubedoom
  namespace: kubedoom
spec:
  type: LoadBalancer
  selector:
    app: kubedoom
  ports:
    - port: 5901
      targetPort: 5900
      protocol: TCP
